version: '3.7'

services:
  tests:
    build:
      context: .
      dockerfile: docker/development.dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test:ci"]